# Generated by Django 5.1.6 on 2025-04-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0002_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.CharField(choices=[('UB', 'Universitat de Barcelona'), ('UAB', 'Universitat Autònoma de Barcelona'), ('UPC', 'Universitat Politècnica de Catalunya'), ('UPF', 'Universitat Pompeu Fabra'), ('URV', 'Universitat Rovira i Virgili'), ('UdG', 'Universitat de Girona'), ('UdL', 'Universitat de Lleida'), ('UOC', 'Universitat Oberta de Catalunya'), ('UVic-UCC', 'Universitat de Vic - Universitat Central de Catalunya'), ('UIC', 'Universitat Internacional de Catalunya'), ('URL', 'Universitat Ramon Llull'), ('UPSA', 'Universitat Abat Oliba CEU')], default='', max_length=64),
        ),
    ]
