# Generated by Django 5.1.6 on 2025-04-17 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('unicat', '0003_user_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('faculty', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('university', models.CharField(choices=[('UB', 'Universitat de Barcelona'), ('UAB', 'Universitat Autònoma de Barcelona'), ('UPC', 'Universitat Politècnica de Catalunya'), ('UPF', 'Universitat Pompeu Fabra'), ('URV', 'Universitat Rovira i Virgili'), ('UdG', 'Universitat de Girona'), ('UdL', 'Universitat de Lleida'), ('UOC', 'Universitat Oberta de Catalunya'), ('UVic-UCC', 'Universitat de Vic - Universitat Central de Catalunya'), ('UIC', 'Universitat Internacional de Catalunya'), ('URL', 'Universitat Ramon Llull'), ('UPSA', 'Universitat Abat Oliba CEU')], default='', max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='resources/')),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
