# Generated by Django 5.1.6 on 2025-04-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0004_comment_event_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('slides', 'Slides'), ('pdf', 'Pdf'), ('video', 'Video'), ('web', 'Web'), ('image', 'Image'), ('audio', 'Audio'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
