# Generated by Django 5.1.6 on 2025-04-17 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0005_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('slides', 'Slides'), ('pdf', 'Pdf'), ('video', 'Video'), ('web', 'Web'), ('image', 'Image'), ('other', 'Other')], default='', max_length=64),
        ),
    ]
