# Generated by Django 5.1.6 on 2025-04-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0006_resource_timestamp_alter_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
    ]
