# Generated by Django 5.1.6 on 2025-04-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0007_event_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(default='', max_length=64),
        ),
    ]
