# Generated by Django 5.1.6 on 2025-04-25 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0008_alter_event_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
