# Generated by Django 5.1.7 on 2025-05-06 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0010_country_erasmus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErasmusProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(default='', max_length=64)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicat.country')),
            ],
            options={
                'verbose_name_plural': 'Erasmus Programs',
                'unique_together': {('university', 'country')},
            },
        ),
        migrations.CreateModel(
            name='ErasmusParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('contact_info', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='unicat.erasmusprogram')),
            ],
            options={
                'unique_together': {('user', 'program')},
            },
        ),
        migrations.DeleteModel(
            name='Erasmus',
        ),
    ]
