# Generated by Django 5.1.6 on 2025-05-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0011_erasmusprogram_erasmusparticipant_delete_erasmus'),
    ]

    operations = [
        migrations.AddField(
            model_name='erasmusparticipant',
            name='interests',
            field=models.TextField(blank=True),
        ),
    ]
