# Generated by Django 5.1.6 on 2025-05-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0012_erasmusparticipant_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erasmusprogram',
            name='country',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
