# Generated by Django 5.1.6 on 2025-05-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0013_alter_erasmusprogram_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='erasmusparticipant',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
