# Generated by Django 5.1.6 on 2025-05-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0014_erasmusparticipant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erasmusprogram',
            name='country',
            field=models.CharField(max_length=255),
        ),
    ]
