# Generated by Django 5.1.6 on 2025-05-19 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0016_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
    ]
