# Generated by Django 5.1.6 on 2025-05-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0018_alter_comment_options_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field_Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Fields of Study',
                'ordering': ['name'],
            },
        ),
    ]
