# Generated by Django 5.1.7 on 2025-05-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0019_field_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='field_of_study',
            field=models.CharField(default='', max_length=64),
        ),
    ]
