# Generated by Django 5.1.6 on 2025-06-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0020_resource_field_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
