# Generated by Django 5.1.6 on 2025-06-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0022_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='faculty',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='university',
            field=models.CharField(blank=True, choices=[('UB', 'Universitat de Barcelona'), ('UAB', 'Universitat Autònoma de Barcelona'), ('UPC', 'Universitat Politècnica de Catalunya'), ('UPF', 'Universitat Pompeu Fabra'), ('URV', 'Universitat Rovira i Virgili'), ('UdG', 'Universitat de Girona'), ('UdL', 'Universitat de Lleida'), ('UOC', 'Universitat Oberta de Catalunya'), ('UVic-UCC', 'Universitat de Vic - Universitat Central de Catalunya'), ('UIC', 'Universitat Internacional de Catalunya'), ('URL', 'Universitat Ramon Llull'), ('UPSA', 'Universitat Abat Oliba CEU')], default='', max_length=64),
        ),
    ]
