# Generated by Django 5.1.6 on 2025-06-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0023_alter_event_faculty_alter_event_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('conference', 'Conference'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('networking', 'Networking'), ('hackathon', 'Hackathon'), ('course', 'Course'), ('open house', 'Open House'), ('other', 'Other')], default='', max_length=64),
        ),
    ]
