# Generated by Django 5.1.6 on 2025-06-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0025_alter_event_description_alter_event_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='university',
            field=models.CharField(blank=True, choices=[('UB', 'Universitat de Barcelona'), ('UAB', 'Universitat Autònoma de Barcelona'), ('UPC', 'Universitat Politècnica de Catalunya'), ('UPF', 'Universitat Pompeu Fabra'), ('URV', 'Universitat Rovira i Virgili'), ('UdG', 'Universitat de Girona'), ('UdL', 'Universitat de Lleida'), ('UOC', 'Universitat Oberta de Catalunya'), ('UVic', 'Universitat de Vic'), ('UIC', 'Universitat Internacional de Catalunya'), ('URL', 'Universitat Ramon Llull'), ('UAO', 'Universitat Abat Oliba CEU (UAO)'), ('EAE', 'EAE Business School'), ('Other', 'Other')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.CharField(choices=[('UB', 'Universitat de Barcelona'), ('UAB', 'Universitat Autònoma de Barcelona'), ('UPC', 'Universitat Politècnica de Catalunya'), ('UPF', 'Universitat Pompeu Fabra'), ('URV', 'Universitat Rovira i Virgili'), ('UdG', 'Universitat de Girona'), ('UdL', 'Universitat de Lleida'), ('UOC', 'Universitat Oberta de Catalunya'), ('UVic', 'Universitat de Vic'), ('UIC', 'Universitat Internacional de Catalunya'), ('URL', 'Universitat Ramon Llull'), ('UAO', 'Universitat Abat Oliba CEU (UAO)'), ('EAE', 'EAE Business School'), ('Other', 'Other')], default='', max_length=64),
        ),
    ]
