# Generated by Django 5.1.6 on 2025-06-12 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0027_country_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='erasmusprogram',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='erasmusprogram',
            name='ar_rank',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='erasmusprogram',
            name='ar_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erasmusprogram',
            name='country_code',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='unicat.country'),
        ),
        migrations.AddField(
            model_name='erasmusprogram',
            name='cpf_rank',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='erasmusprogram',
            name='cpf_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erasmusprogram',
            name='er_rank',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='erasmusprogram',
            name='er_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erasmusprogram',
            name='focus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='erasmusprogram',
            name='fsr_rank',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='erasmusprogram',
            name='fsr_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erasmusprogram',
            name='ger_rank',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='erasmusprogram',
            name='ger_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erasmusprogram',
            name='ifr_rank',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='erasmusprogram',
            name='ifr_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erasmusprogram',
            name='irn_rank',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='erasmusprogram',
            name='irn_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erasmusprogram',
            name='isr_rank',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='erasmusprogram',
            name='isr_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erasmusprogram',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erasmusprogram',
            name='rank',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='erasmusprogram',
            name='research',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='erasmusprogram',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='erasmusprogram',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='erasmusprogram',
            name='sus_rank',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='erasmusprogram',
            name='sus_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='erasmusprogram',
            name='country',
        ),
    ]
