# Generated by Django 5.1.6 on 2025-06-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0028_alter_erasmusprogram_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
