# Generated by Django 5.1.6 on 2025-06-12 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0030_remove_country_id_remove_field_study_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erasmusprogram',
            name='country_code',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='unicat.country'),
        ),
    ]
