# Generated by Django 5.1.6 on 2025-06-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0031_alter_erasmusprogram_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='erasmusprogram',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
