# Generated by Django 5.1.6 on 2025-06-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0032_erasmusprogram_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='erasmusprogram',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='erasmus_images/'),
        ),
    ]
