# Generated by Django 5.1.6 on 2025-06-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0033_erasmusprogram_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='erasmusprogram',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
