# Generated by Django 5.1.6 on 2025-06-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0002_auto_20250615_1950'),
        ('unicat', '0003_add_order_field_manually'),
    ]

    operations = [
    ]
