# Generated by Django 5.1.6 on 2025-06-21 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0005_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='num_stars',
            field=models.FloatField(choices=[(1.0, '1 star'), (1.5, '1.5 stars'), (2.0, '2 stars'), (2.5, '2.5 stars'), (3.0, '3 stars'), (3.5, '3.5 stars'), (4.0, '4 stars'), (4.5, '4.5 stars'), (5.0, '5 stars')], default=0),
        ),
        migrations.CreateModel(
            name='ErasmusReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('rating', models.FloatField(default=0)),
                ('academic_rating', models.FloatField(default=0)),
                ('housing_rating', models.FloatField(default=0)),
                ('social_rating', models.FloatField(default=0)),
                ('city_rating', models.FloatField(default=0)),
                ('tips', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='unicat.erasmusprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Erasmus Reviews',
                'unique_together': {('user', 'program')},
            },
        ),
    ]
