# Generated by Django 5.1.6 on 2025-06-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0006_alter_ratings_num_stars_erasmusreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
