# Generated by Django 5.1.6 on 2025-06-21 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0007_delete_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='erasmusprogram',
            name='cached_average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_stars', models.FloatField(choices=[(1.0, '1 star'), (1.5, '1.5 stars'), (2.0, '2 stars'), (2.5, '2.5 stars'), (3.0, '3 stars'), (3.5, '3.5 stars'), (4.0, '4 stars'), (4.5, '4.5 stars'), (5.0, '5 stars')], default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('erasmus_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='unicat.erasmusprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ratings',
                'unique_together': {('user', 'erasmus_program')},
            },
        ),
    ]
