# Generated by Django 5.1.6 on 2025-06-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0008_erasmusprogram_cached_average_rating_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erasmusreview',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
