# Generated by Django 5.1.6 on 2025-06-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0009_alter_erasmusreview_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
