# Generated by Django 5.1.6 on 2025-06-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0010_delete_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erasmusreview',
            name='academic_rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='erasmusreview',
            name='city_rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='erasmusreview',
            name='housing_rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='erasmusreview',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='erasmusreview',
            name='social_rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
