# Generated by Django 5.1.6 on 2025-06-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0011_alter_erasmusreview_academic_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='inscription_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
