# Generated by Django 5.1.6 on 2025-06-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0012_event_inscription_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
