# Generated by Django 5.1.6 on 2025-06-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0013_resource_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
