# Generated by Django 5.1.6 on 2025-06-29 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0014_alter_resource_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='updated_at',
        ),
    ]
