# Generated by Django 5.1.6 on 2025-06-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0015_remove_resource_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
