# Generated by Django 5.1.6 on 2025-06-29 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0018_event_created_at_event_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
    ]
