# Generated by Django 5.1.6 on 2025-06-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0019_remove_event_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
