# Generated by Django 5.1.6 on 2025-06-30 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0021_remove_event_created_at_remove_event_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
