# Generated by Django 5.1.6 on 2025-06-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0023_favouriteerasmusprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_info',
            field=models.TextField(blank=True),
        ),
    ]
