# Generated by Django 5.1.6 on 2025-07-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0024_profile_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('conference', 'Conference'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('networking', 'Networking'), ('hackathon', 'Hackathon'), ('course', 'Course'), ('open house', 'Open House'), ('party', 'Party'), ('other', 'Other')], default='', max_length=64),
        ),
    ]
