# Generated by Django 5.1.6 on 2025-07-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0026_user_is_email_verified_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_event_creation_permissions',
            field=models.BooleanField(default=False),
        ),
    ]
