# Generated by Django 5.1.6 on 2025-07-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0027_user_has_event_creation_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='has_event_creation_permissions',
            new_name='is_institution',
        ),
    ]
