# Generated by Django 5.1.6 on 2025-07-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0028_rename_has_event_creation_permissions_user_is_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='program_file',
            field=models.FileField(blank=True, null=True, upload_to='event_programs/'),
        ),
    ]
