# Generated by Django 5.1.6 on 2025-07-01 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0030_eventparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('page_url', models.URLField(max_length=500)),
                ('severity', models.CharField(choices=[('low', 'Low - Minor issue'), ('medium', 'Medium - Noticeable problem'), ('high', 'High - Major functionality broken'), ('critical', 'Critical - App unusable')], default='medium', max_length=20)),
                ('report_type', models.CharField(choices=[('bug', 'Bug/Error'), ('ui', 'UI/Design Issue'), ('performance', 'Performance Issue'), ('feature', 'Feature Request'), ('other', 'Other')], default='bug', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('user_agent', models.TextField(blank=True)),
                ('screen_resolution', models.CharField(blank=True, max_length=50)),
                ('browser_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bug Report',
                'verbose_name_plural': 'Bug Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
