# Generated by Django 5.1.6 on 2025-07-01 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0031_bugreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugreport',
            name='email',
        ),
    ]
