# Generated by Django 5.1.6 on 2025-07-01 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0032_remove_bugreport_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugreport',
            name='browser_info',
        ),
        migrations.RemoveField(
            model_name='bugreport',
            name='screen_resolution',
        ),
        migrations.RemoveField(
            model_name='bugreport',
            name='user_agent',
        ),
    ]
