# Generated by Django 5.1.6 on 2025-07-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0034_alter_eventparticipant_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='events_count',
            field=models.IntegerField(default=0),
        ),
    ]
