# Generated by Django 5.1.6 on 2025-07-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0035_user_events_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='erasmusprogram',
            name='static_image',
            field=models.CharField(blank=True, help_text="Nom del fitxer d'imatge a static/unicat/images/erasmus/", max_length=200, null=True),
        ),
    ]
