# Generated by Django 5.1.6 on 2025-07-02 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0036_erasmusprogram_static_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erasmusprogram',
            name='image',
        ),
    ]
