# Generated by Django 5.1.6 on 2025-07-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0037_remove_erasmusprogram_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erasmusprogram',
            name='university',
            field=models.CharField(default='', max_length=200),
        ),
    ]
