# Generated by Django 5.1.6 on 2025-07-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0038_increase_university_name_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resource',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
    ]
