# Generated by Django 5.1.6 on 2025-07-06 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicat', '0039_alter_resource_description_alter_resource_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erasmusparticipant',
            name='name',
        ),
    ]
